### ISSUE TITLE
URL leads to 404 Error

### ISSUE THREAD

**Issue by Alonski** [emberjs/ember-collection#147] opened 2017-03-29 12:59 UTC
https://emberjs.com/ember-collection/
In Description
Leads to a 404 error...

**Comment by locks** [comment] 2017-03-29 13:55
@Alonski hi, can you tell us where did you get linked from?

**Comment by lolmaus** [comment] 2017-06-07 10:01
The solution is quite simple:

1. `ember i ember-cli-deploy`
2. `ember i ember-cli-deploy-build`
3. `ember i ember-cli-deploy-ghpages`
4. At the bottom of `config/environment.js`, find the `if (environment === 'production')` section and add `ENV.rootURL = '/ember-collection';`.
5. In the `config/deploy.js` generated during addon installation, add this:

    ```js
    ghpages : {
      gitRemoteUrl : 'git@github.emberjs/ember-collection.git'
    }
    ```

There's something causing a redirect to emberjs.com. If it's caused by the current GitHub Pages website, we're good. If by something else, the reason has to be found and eliminated.

**Comment by locks** [comment] 2017-06-07 10:10
Can you send a PR @lolmaus? I'm closing the issue as we fixed it by removing the link from the repository description :P

**Closed** 2017-06-07 10:10 UTC
