### ISSUE TITLE
Collection cells overlap pop-overs

### ISSUE THREAD

**Issue by flyswatter** [emberjs/ember-collection#89] opened 2016-02-01 23:19 UTC
I use a `position: fixed` element for a pop-over effect in an application, and EmberCollection seems to use 3D transforms in a way that makes lower cells initially block pop-overs from higher cells:

![screen shot 2016-02-01 at 3 16 06 pm](https://cloud.githubusercontent.com/assets/542863/12734694/0dea0178-c8f7-11e5-8ca6-42cb2a60fc3a.png)

After scrolling down and up again, there is a chance the pop-over is unobstructed.

I'm not very familiar with how these 3D transformations are applied within EmberCollection, any tips on making a pop-over visible originating from one?

**Comment by raytiley** [comment] 2016-02-01 23:32
I had this problem when I first started using `list-view` / `ember-collection`. The issue is the transform creates a new stacking context. You could ether.

A) Extend the layout and generate CSS that doesn't use the transform so it's compatible with what you are rendering in the cells.

B) Use something like [Ember Wormhole](https://github.com/yapplabs/ember-wormhole) and / or[Ember Tether](https://github.com/yapplabs/ember-tether) to render the element somewhere else where it can overlay the items.

**Comment by flyswatter** [comment] 2016-02-08 18:38
By the way, you were totally on point with this feedback, thank you, I was able to implement a solution based on your response (did a global modal type solution instead, kindof side-stepping the ember-wormhole style solution).

**Comment by raytiley** [comment] 2016-02-14 01:32
@flyswatter going to close this for now since I think it's outside the scope of `ember-collection` to handle this. If it comes up frequently we can probably add something to the docs.

**Closed by raytiley** 2016-02-14 01:32 UTC
